spring.application.name=bitespeed
spring.datasource.url=jdbc:postgresql://localhost:5432/identitydb
spring.datasource.username=postgres
spring.datasource.password=0308bhuvanY

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect